name: food_delivery
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  intl: ^0.17.0
  dio: ^4.0.6
  injectable: ^1.5.3
  get_it: ^7.2.0
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  shared_preferences: ^2.0.15
  flutter_advanced_drawer: ^1.3.2
  icons_launcher: ^1.2.1

   

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_resolvers: ^2.0.9
  build_runner: ^2.2.0
  injectable_generator: ^1.5.4
  flutter_native_splash: ^2.2.7 

flutter_native_splash:
  background_image: assets/images/splash_screen/splash.png
  android: true
  ios: true 
  android_12: 
    image_dark: assets/images//splash_screen/logo_food.png
    image: assets/images//splash_screen/logo_food.png
    color: "000000"

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/icons/icon_app.png'




flutter:

  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash_screen/
    - assets/images/on_boarding_screen/
    - assets/images/icons/
    - assets/images/icons/burger/
    - assets/images/auth_screen/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset:  assets/fonts/RobotoCondensed-Regular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
